"""Added ForeignKey and relationship between Client and Appointment

Revision ID: 96f0fbbeefab
Revises: 
Create Date: 2024-12-27 06:02:17.459636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f0fbbeefab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('appointment_note', sa.Text(), nullable=True),
    sa.Column('appointment_price', sa.Float(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.lawyer_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.drop_table('appointment')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specialization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('case_description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_constraint('case_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('case_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['client_id'])
        batch_op.create_foreign_key(None, 'specialization', ['specialization_id'], ['specialization_id'])
        batch_op.drop_column('specialization')
        batch_op.drop_column('client')
        batch_op.drop_column('id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_fname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('client_lname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('client_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('client_password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('client_state',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('lawyer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('document_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('document_file',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint('document_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lawyer', ['lawyer_id'], ['lawyer_id'])
        batch_op.drop_column('id')
        batch_op.drop_column('lawyer')

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.alter_column('lawyer_lname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('lawyer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lawyer_password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('lawyer_state',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('lawyer_profile_picture',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('lawyer_specialization',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('specialization')
        batch_op.drop_index('state')
        batch_op.create_unique_constraint(None, ['lawyer_license_number'])

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.alter_column('lga_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('lga_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lawyer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.alter_column('reference_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['reference_number'])
        batch_op.drop_constraint('payment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('payment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['client_id'])
        batch_op.create_foreign_key(None, 'lawyer', ['lawyer_id'], ['lawyer_id'])
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['appointment_id'])
        batch_op.drop_column('appointment')
        batch_op.drop_column('client')
        batch_op.drop_column('id')
        batch_op.drop_column('lawyer')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lawyer_id', sa.Integer(), nullable=False))
        batch_op.drop_index('review_client')
        batch_op.drop_index('review_lawyer')
        batch_op.drop_constraint('review_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['client_id'])
        batch_op.create_foreign_key(None, 'lawyer', ['lawyer_id'], ['lawyer_id'])
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['appointment_id'])
        batch_op.drop_column('appointment')
        batch_op.drop_column('id')
        batch_op.drop_column('review_client')
        batch_op.drop_column('review_lawyer')

    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['specialization_name'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_lawyer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('review_client', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('appointment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_ibfk_1', 'appointment', ['appointment'], ['appointment_id'])
        batch_op.create_index('review_lawyer', ['review_lawyer'], unique=True)
        batch_op.create_index('review_client', ['review_client'], unique=True)
        batch_op.drop_column('lawyer_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('review_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lawyer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('client', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('appointment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_2', 'lawyer', ['lawyer'], ['lawyer_id'])
        batch_op.create_foreign_key('payment_ibfk_1', 'client', ['client'], ['client_id'])
        batch_op.create_foreign_key('payment_ibfk_3', 'appointment', ['appointment'], ['appointment_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('reference_number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('client_id')
        batch_op.drop_column('lawyer_id')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.alter_column('lga_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('lga_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('state', ['state_id'], unique=False)
        batch_op.create_index('specialization', ['specialization_id'], unique=False)
        batch_op.alter_column('lawyer_specialization',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('lawyer_profile_picture',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('lawyer_state',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('lawyer_password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('lawyer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('lawyer_lname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lawyer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_ibfk_1', 'lawyer', ['lawyer'], ['lawyer_id'])
        batch_op.alter_column('document_file',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('document_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('lawyer_id')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_state',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('client_password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('client_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('client_lname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('client_fname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('client', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specialization', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_ibfk_2', 'client', ['client'], ['client_id'])
        batch_op.create_foreign_key('case_ibfk_1', 'specialization', ['specialization'], ['specialization_id'])
        batch_op.alter_column('case_description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('specialization_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('case_id')

    op.create_table('appointment',
    sa.Column('appointment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appointment_date', mysql.DATETIME(), nullable=False),
    sa.Column('appointment_note', mysql.TEXT(), nullable=True),
    sa.Column('appointment_price', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lawyer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appointment_time', mysql.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name='appointment_ibfk_2'),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name='appointment_ibfk_4'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.lawyer_id'], name='appointment_ibfk_1'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.lawyer_id'], name='appointment_ibfk_3'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###
